
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bftuoerxiyocfputahrx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJmdHVvZXJ4aXlvY2ZwdXRhaHJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5Njg5OTcsImV4cCI6MjA1NzU0NDk5N30.Os1fTswoDdSO41H4N7I4n3P1FWSjHVzB1zS5BiOZrHs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
